docker-entrypoint.sh

The error will be returned with the return value at the first execution.
It is guessed that rm returns "exit 1" at empty directory.
before
```
$docker run -it --rm -p 5656:5656 -v data:/var/lib/edgedb/data edgedb/edgedb
rm: cannot remove '/var/run/edgedb/*': No such file or directory
```
after
```
$docker build -t edgedb:1.0 --build-arg version=1-alpha1 .
$docker run -it --rm -p 5656:5656 -v data:/var/lib/edgedb/data edgedb:1.0
Bootstrapping EdgeDB instance...
CONFIGURE SYSTEM
CONFIGURE SYSTEM
INFO 1 2019-04-20 09:59:31,814 edb.server: EdgeDB server (1.0.alpha.1) starting.
INFO 1 2019-04-20 09:59:34,229 edb.server: Serving on 0.0.0.0:5656
INFO 1 2019-04-20 09:59:34,229 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2019-04-20 09:59:34,230 edb.server: Serving admin on …
```

Fix remove directory return error

---

.github/workflows/test.yml
Dockerfile
docker-entrypoint.sh
tests/auth.bats
tests/bootstrap.bats
tests/bootstrap/Dockerfile
tests/bootstrap/edgedb-bootstrap.d/01.sh
tests/bootstrap/edgedb-bootstrap.d/02.edgeql
tests/bootstrap/edgedb-bootstrap.d/03.edgeql
tests/bootstrap/edgedb-bootstrap.edgeql
tests/schema.bats
tests/schema/Dockerfile
tests/schema/dbschema/default.esdl
tests/schema/dbschema/migrations/00001.edgeql

This is largely untested for now.
1. Add support of docker-entrypoints.d (fixes #3). Scripts are run by
a user passed to docker (root by default).
2. If `/edgedb-bootstrap.edgeql` exists, use it as `--bootstrap-script`
3. Else, if `EDGEB_BOOTSTRAP_COMMAND` exists, pass it as `--bootstrap-command`
4. Else, if `EDGEDB_PASSWORD_HASH` exists, create `EDGEDB_USER` or set
that password for user `edgedb` (uses encoded password)
5. Else, if `EDGEDB_PASSWORD` exists, create `EDGEDB_USER` or set
password (this is to share settings in docker-compose.yaml easier)
6. If `EDGEDB_DATABASE` is not `edgedb` create that database
7. Run all `/edgedb-bootstrap/*.sh` scripts after configuration above
(and before restarting the database). Scripts are run as `edgedb`
user if container is run by root.
8. Execute …

New setup of dockerfile

---

.dockerignore
.editorconfig
Dockerfile
README.md
docker-entrypoint.sh
tests/bootstrap.bats

Reorganize `docker-entrypoint.sh` code into functions for better 
maintainability and implement the following improvements:
- add support for `EDGEDB_PASSWORD_FILE` and other similar variables to
facilitate a more secure specification of secrets;
- add support for remote PostgreSQL clusters via `EDGEDB_POSTGRES_DSN`
or `--postgres-dsn`;
- add support for `EDGEDB_PORT` (or `--port`) and `EDGEDB_BIND_ADDRESS`
(or `--bind-address`) to modify server listening parameters, which
might be useful for `host` networking mode;
- run bootstrap and migrations with a temporary server on a random port
to avoid exposing the server to the network in half-initialized state.

Rewrite docker-entrypoint.sh

---

README.md
docker-entrypoint-funcs.sh
tests/auth.bats
tests/bootstrap.bats
tests/schema.bats

`edgedb authenticate` is no more, use `edgedb instance link`.
Depends on a CLI fix in edgedb/edgedb-cli#446

Fix tests and adjust the TLS notice

---

README.md
docker-entrypoint-funcs.sh
tests/auth.bats
tests/bootstrap.bats
tests/compose/docker-compose.yml
tests/schema.bats

fixes https://github.com/edgedb/edgedb/issues/2643
This change disambiguates server environment variables from client environment variables.

Add SERVER prefix to environment variable names

---

README.md
docker-entrypoint-funcs.sh

Wire up `EDGEDB_SERVER_INSECURE_DEV_MODE` in the entrypoint.  Notably,
this doesn't use the `--insecure-dev-mode` server argument and
instead implements the implied effects directly to work better with the
entrypoint logic.

Add support for EDGEDB_SERVER_INSECURE_DEV_MODE

---

README.md

Update `EDGEDB_SERVER_DATADIR` default value in README in accordance to:
https://github.com/edgedb/edgedb-docker/blob/37e6ed933e317beaaad8935e01cabe8249698072/docker-entrypoint-funcs.sh#L302

Fix `EDGEDB_SERVER_DATADIR` default value in README

---

docker-entrypoint-funcs.sh

This adds a way to specify a given parameter value in an arbitrary
environment variable given via `<PARAM>_ENV`.  For example:
EDGEDB_SERVER_BACKEND_DSN_ENV=DATABASE_URL
The above is especially useful when running the edgedb container from a
host that allows linking hosted PostgreSQL instances, like DigitalOcean
or Fly.io (both use `DATABASE_URL`)

Allow specifying an alternative environment variable for a param

---

Dockerfile
README.md
docker-entrypoint-funcs.sh
tests/auth.bats
tests/bootstrap.bats
tests/compose.bats
tests/compose_dev_mode.bats
tests/other.bats
tests/schema.bats

The entrypoint now supports `EDGEDB_TLS_CERT_MODE` added in
edgedb/edgedb#3213.
Alongside this a set of cleanups:
* use `--emit-server-status` to wait for server and extract the
port and TLS cert location like we do everywhere else;
* significantly simplify temp server waiting and error handling
logic;
* stop exporting variables into the environment and enable
bash `nounset`.

Add support for `EDGEDB_TLS_CERT_MODE` and do a bunch of cleanups

---

README.md
docker-entrypoint-funcs.sh

Replace `EDGEDB_SERVER_HIDE_GENERATED_CERT` with
`EDGEDB_DOCKER_SHOW_GENERATED_CERT=always|never`, and
`EDGEDB_SERVER_SKIP_MIGRATIONS` with
`EDGEDB_DOCKER_APPLY_MIGRATIONS=always|never`.  Also,
correct spelling of `EDGEDB_SERVER_DOCKER_LOG_LEVEL` to
`EDGEDB_DOCKER_LOG_LEVEL` for prefix consistency.

Replace the remaining boolean parameters with enum

---

Dockerfile
docker-entrypoint-funcs.sh
edgedb-show-secrets.sh
tests/show_secrets.bats

This adds `edgedb-show-secrets.sh` to the container as a way to easily
obtain the raw value of a specific known secret, or a set of specified
secrets, or all of known secrets, in TOML format:
```
docker exec <container> edgedb-show-secrets.sh \
--format=toml EDGEDB_SERVER_TLS_CERT EDGEDB_SERVER_TLS_KEY
```
or
```
docker exec <container> edgedb-show-secrets.sh \
--format=shell --all
```
This helper is especially useful when one wants to preserve the
generated TLS certificate and key as a secret on a hosting platform.

Add a script to export secrets

---

docker-entrypoint-funcs.sh
edgedb-show-secrets.sh
tests/other.bats
tests/testbase.bash

Don't attempt to write outside of `/tmp` when the container isn't
running as root.

Fix running as non-root

---

docker-entrypoint-funcs.sh
tests/bootstrap.bats
tests/bootstrap/Dockerfile
tests/bootstrap/dbschema/migrations/00001.edgeql
tests/bootstrap/dbschema/migrations/00002.edgeql
tests/bootstrap/edgedb-bootstrap-late.d/04.sh
tests/bootstrap/edgedb-bootstrap-late.d/05.edgeql

Currently, `/edgedb-bootstrap.d` is executed _before_ migrations are
applied, which could be inconvenient if custom bootstrap relies on the
schema.  This lets putting bootstrap parts in `/edgedb-bootstrap-late.d`
to be executed _after_ the migrations have been applied.

Add support for "late" bootstrap hooks

---

docker-entrypoint-funcs.sh
tests/bootstrap/edgedb-bootstrap-late.d/04.sh
tests/bootstrap/edgedb-bootstrap.d/01.sh

With recent CLI changes using `--admin` no longer works (because
`EDGEDB_HOST` no longer allows Unix sockets).  Since bootstrap server
only listens on loopback we can use TCP with Trust default authentication
method.  In case an explicit auth is configured, use `EDGEDB_USER` and
`EDGEDB_PASSWORD` as specified in the environment.

Stop using Unix sockets for bootstrap

---

docker-entrypoint-funcs.sh
tests/bootstrap.bats

we need to pass the tenant_id as environemnt variable to the temp server. Otherwise the bootstrap and check initalize steps will start without the tenant_id. This leads to a bootstrap of a wrong tenant and afterwards a check failure, because the instance seems to be not initialized.

fix #72 tenant-id isn't supported

---

docker-entrypoint-funcs.sh
tests/bootstrap.bats
tests/bootstrap/Dockerfile
tests/bootstrap/dbschema/migrations/00001.edgeql
tests/bootstrap/dbschema/migrations/00002.edgeql
tests/bootstrap/edgedb-bootstrap.edgeql
tests/compose.bats
tests/compose_dev_mode.bats
tests/testbase.bash

3.x added support for the `EDGEDB_SERVER_BOOTSTRAP_ONLY` environment
variable, which broken the analogous flow in the Docker image
entrypoint.

Fix `EDGEDB_SERVER_BOOTSTRAP_ONLY` mode on 3.x

---

docker-entrypoint-funcs.sh

#74 blocked the PG* vars from being passed through.
Manually collect and send them through to the new isolated env.

Restore PG* env var handling

---

docker-entrypoint-funcs.sh

I'm not sure if `--jose-key-mode` needs to be exposed. It will use the given one if given or generate if not given, right?

Handle JWS Key from env var / command args

---

docker-entrypoint-funcs.sh
tests/auth.bats

For prior-5.0 servers, `EDGEDB_SERVER_DEFAULT_BRANCH` is ignored with a warning.
For 5.0 and above, `EDGEDB_SERVER_DEFAULT_BRANCH` is preferred but `EDGEDB_SERVER_DATABASE` is also accepted with a deprecation warning.

Add EDGEDB_SERVER_DEFAULT_BRANCH

---

Dockerfile
docker-entrypoint-funcs.sh
edgedb-show-secrets.sh
tests/show_secrets.bats
tests/testbase.bash

This doesn't do anything about the environment variables yet, but allows
building images of gel-server.

Gel branding

---

docker-entrypoint-funcs.sh

Also, rather than sending SIGKILL after the first timeout, send SIGTERM
again (thus requesting the server to stop being graceful and shutdown
ASAP), and if after another 10s the server does not exit, kill it.

Wait longer for server to shut down after bootstrap
